from utils import StringFunction, resolve, get_proteins

stats = {'stats5': {'version'         : 'stats5',
                    'ifp_version'     : 'ifp3',
                    'mcss_version'    : 'mcss14',
                    'docking_version' : 'glide12',
                    'pdb_order'       : 'First',
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'weighting'       : 'absolute',
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,
                    'gscore_domain'   : (-16, 2),
                    'gscore_points'   : 1000,
                    'gscore_sd'       : 0.4},

         'stats6': {'version'         : 'stats6',
                    'ifp_version'     : 'ifp4',
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,
                    'weighting'       : 'unweighted',
                    'gscore_domain'   : (-16, 2),
                    'gscore_points'   : 1000,
                    'gscore_sd'       : 0.4},

         'stats7': {'version'         : 'stats7',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,
                    'weighting'       : 'unweighted',
                    'gscore_domain'   : (-16, 2),
                    'gscore_points'   : 1000,
                    'gscore_sd'       : 0.4},

         'stats8': {'version'         : 'stats8',
                    'ifp_version'     : 'ifp6',
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,
                    'weighting'       : 'unweighted',
                    'gscore_domain'   : (-16, 2),
                    'gscore_points'   : 1000,
                    'gscore_sd'       : 0.4},

         'stats9': {'version'         : 'stats9',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : True,
                    'ligands_equal'   : True,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100},
         
         'stats10': {'version'        : 'stats10',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.03,
                    'stats_points'    : 100},

        'stats11': {'version'        : 'stats11',
                    'ifp_version'     : 'ifp7',
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100},

        'stats12': {'version'         : 'stats12', # Uses tanimoto coeff.
                    'ifp_version'     : 'ifp5',    # Must hardcode.
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
         'stats13': {'version'        : 'stats13', # Uses tanimoto coeff.
                    'ifp_version'     : 'ifp5',    # Must hardcode.
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : True,
                    'ligands_equal'   : True,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats14': {'version'         : 'stats14', # Uses tanimoto coeff.
                    'ifp_version'     : 'ifp5',    # Must hardcode.
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : True,
                    'ligands_equal'   : True,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats15': {'version'         : 'stats15', # Uses tanimoto coeff.
                    'ifp_version'     : 'ifp5',    # Must hardcode.
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : True,
                    'ligands_equal'   : True,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 1,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats16': {'version'         : 'stats16', # Uses psuedo-tanimoto coeff.
                    'ifp_version'     : 'ifp5',    # Must hardcode.
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : True,
                    'ligands_equal'   : True,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats17': {'version'         : 'stats17', # Uses psuedo-tanimoto coeff.
                    'ifp_version'     : 'ifp5',    # Must hardcode.
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats18': {'version'         : 'stats18',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats19': {'version'         : 'stats19',
                    'metric'          : 'maxoverlap',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('max'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats20': {'version'         : 'stats20',
                    'metric'          : 'maxoverlap',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('max'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'XP',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats21': {'version'         : 'stats21',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats22': {'version'         : 'stats22',
                    'metric'          : 'maxoverlap',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats23': {'version'         : 'stats23',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.02,
                    'stats_points'    : 100,},
        'stats24': {'version'         : 'stats24', # min instead of geometric mean.
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats25': {'version'         : 'stats25', # Exclude interaction from stats if no poses make one.
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats26': {'version'         : 'stats26',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats27': {'version'         : 'stats27', # psuedo of 20 for contacts.
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},

        'stats28': {'version'         : 'stats28', # psuedo of 40 for contacts.
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats29': {'version'         : 'stats29', # hybrid
                    'metric'          : 'hybrid',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats30': {'version'         : 'stats30',
                    'metric'          : 'tanimoto-maxoverlap',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats31': {'version'         : 'stats31',
                    'metric'          : 'tanimoto-maxoverlap-exclude',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100,},
        'stats32': {'version'         : 'stats32',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100},
         # Here down remove all but CDK2.
        'stats33': {'version'         : 'stats33',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100},
        'stats34': {'version'         : 'stats34',
                    'metric'          : 'tanimoto-exclude',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100},
        'stats35': {'version'         : 'stats35',
                    'metric'          : 'tanimoto-exclude',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'native_poses'    : 100,
                    'reference_poses' : 1,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100},
          'stats36': {'version'       : 'stats36',
                    'metric'          : 'tanimoto-exclude',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'native_poses'    : 100,
                    'reference_poses' : 1,
                    'stats_sd'        : 0.03,
                    'stats_points'    : 100},
          'stats37': {'version'       : 'stats37',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.05,
                    'stats_points'    : 100},
          'stats38': {'version'       : 'stats38',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.03,
                    'stats_points'    : 100},
          'stats39': {'version'       : 'stats39',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : True,
                    'ligands_equal'   : True,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100},
          'stats40': {'version'       : 'stats40',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : True,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100},
          'stats41': {'version'       : 'stats41',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'mcss_domain'     : (0, 6),
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.03,
                    'stats_points'    : 100},
          'stats42': {'version'       : 'stats42',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'mcss_domain'     : (0, 6),
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.05,
                    'stats_points'    : 100},
          'stats43': {'version'       : 'stats43',
                    'metric'          : 'tanimoto-maxoverlap',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.03,
                    'stats_points'    : 100},
          'stats44': {'version'       : 'stats44',
                    'metric'          : 'tanimoto-maxoverlap',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100},
          'stats45': {'version'       : 'stats45',
                    'metric'          : 'maxoverlap',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.07,
                    'stats_points'    : 100},
          'stats46': {'version'       : 'stats46',
                    'metric'          : 'tanimoto',
                    'ifp_version'     : 'ifp5',
                    'mcss_version'    : 'mcss16',
                    'mcss_func'       : StringFunction('min'),
                    'mcss_rel_min'    : 0.5,
                    'mcss_abs_min'    : 10,
                    'docking_version' : 'confgen_es4',
                    'pdb_order'       : 'First',
                    'poses_equal'     : False,
                    'ligands_equal'   : False,
                    'native_thresh'   : 2.0,
                    'n_ligs'          : 20,
                    'max_poses'       : 100,
                    'stats_sd'        : 0.02,
                    'stats_points'    : 100},
         }

# for stats in stats32 stats33 stats34 stats35 stats36 stats37 stats38 stats39 stats40; do ./main.py score_controller run_pdb $stats; done;

IFP = {'ifp3': {'version': 'ifp3',
                'hbond_dist_opt': 2.5,
                'hbond_dist_cut': 3.0,
                'hbond_angle_opt': 60.0,
                'hbond_angle_cut': 90.0,
                'sb_dist_opt': 4.0,
                'sb_dist_cut': 5.0,
                'pipi_dist_opt': 4.5,
                'pipi_dist_cut': 6.0,
                'contact_scale_opt': 1.25,
                'contact_scale_cut': 1.75},

       'ifp4': {'version'  : 'ifp4', # Cutoffs same as in ifp3, but ifp code changed.
                'hbond_dist_opt': 2.5,
                'hbond_dist_cut': 3.0,
                'hbond_angle_opt': 60.0,
                'hbond_angle_cut': 90.0,
                'sb_dist_opt': 4.0,
                'sb_dist_cut': 5.0,
                'pipi_dist_opt': 4.5,
                'pipi_dist_cut': 6.0,
                'contact_scale_opt': 1.25,
                'contact_scale_cut': 1.75},

       'ifp5': {'version'  : 'ifp5', # Cutoffs same as in ifp4, but ifp code changed.
                'hbond_dist_opt': 2.5,
                'hbond_dist_cut': 3.0,
                'hbond_angle_opt': 60.0,
                'hbond_angle_cut': 90.0,
                'sb_dist_opt': 4.0,
                'sb_dist_cut': 5.0,
                'pipi_dist_opt': 4.5,
                'pipi_dist_cut': 6.0,
                'contact_scale_opt': 1.25,
                'contact_scale_cut': 1.75},

       'ifp6': {'version'  : 'ifp6',
                'hbond_dist_opt': 2.75,
                'hbond_dist_cut': 5.0,
                'hbond_angle_opt': 60.0,
                'hbond_angle_cut': 90.0,
                'sb_dist_opt': 3.0,
                'sb_dist_cut': 6.0,
                'pipi_dist_opt': 7.75,
                'pipi_dist_cut': 9.0,
                'contact_scale_opt': 1.25,
                'contact_scale_cut': 1.75},

       'ifp7': {'version'  : 'ifp7',
                'hbond_dist_opt': 2.5,
                'hbond_dist_cut': 2.5,
                'hbond_angle_opt': 60.0,
                'hbond_angle_cut': 60.0,
                'sb_dist_opt': 4.0,
                'sb_dist_cut': 4.0,
                'pipi_dist_opt': 7.75,
                'pipi_dist_cut': 9.0,
                'contact_scale_opt': 1.25,
                'contact_scale_cut': 1.75},
     }

feature_defs = {
    'mcss'           :[],
    'sb'             :[1],
    'hbond'          :[2,3],
    'hbond_donor'    :[2],
    'hbond_acceptor' :[3],
    'pipi'           :[6],
    'contact'        :[11]
}

paths = {'CODE': '~/combind',
         'DATA': '/oak/stanford/groups/rondror/users/jpaggi/bpp_data',
         'STATS': '/oak/stanford/groups/rondror/users/jpaggi/statistics',
         'ROOT': '{DATA}/{protein}',
         'HELPERS': '{ROOT}/chembl/helpers',
         'PREPARED_ROOT': '{ROOT}/ligands/prepared_ligands',
         'PREPARED': '{PREPARED_ROOT}/{ligand}/{ligand}_out.mae',
         'GRID_ROOT': '{ROOT}/docking/grids',
         'GRID': '{GRID_ROOT}/{struct}/{struct}.zip',
         'DOCK': '{ROOT}/docking/{docking_version}/{ligand}-to-{struct}',
         'DOCK_PV': '{DOCK}/{ligand}-to-{struct}_pv.maegz',
         'DOCK_REPT': '{DOCK}/{ligand}-to-{struct}.rept',
         'DOCK_RMSD': '{DOCK}/rmsd.csv',
         'IFP':  '{ROOT}/ifp/{ifp_version}/{ligand}-to-{struct}-{docking_version}.fp',
         'XTAL_IFP':'{ROOT}/ifp/{ifp_version}/{pdb}_struct.fp',
         'MCSS': '{ROOT}/mcss/{mcss_version}',
         }
paths = resolve(paths)

exclude = ['D2', 'CHRM3', 'A2AR', 'F11',
           'CHK1', 'MEK1', 'MAPK14', 'PLK1', 'JAK2', 'BRAF']
proteins = get_proteins(paths, exclude)
